max_width = 110
use_small_heuristics = "Max"
edition = "2021"
newline_style = "Unix"
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
wrap_comments = true
format_code_in_doc_comments = true
