name: Dependency Review

on:
  pull_request:
    branches: [main, develop]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Review Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          deny-licenses: GPL-2.0, LGPL-2.0, AGPL-3.0
          comment-summary-in-pr: always

  cargo-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo audit (main)
        run: cargo audit

      - name: Run cargo audit (desktop)
        working-directory: ./desktop/src-tauri
        run: cargo audit

      - name: Run cargo audit (webui)
        working-directory: ./webui
        run: cargo audit

  cargo-outdated:
    name: Check Outdated Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-outdated
        run: cargo install cargo-outdated

      - name: Check outdated dependencies (main)
        run: cargo outdated --exit-code 1 --format json > outdated-main.json || true

      - name: Check outdated dependencies (desktop)
        working-directory: ./desktop/src-tauri
        run: cargo outdated --exit-code 1 --format json > outdated-desktop.json || true

      - name: Check outdated dependencies (webui)
        working-directory: ./webui
        run: cargo outdated --exit-code 1 --format json > outdated-webui.json || true

      - name: Upload outdated report
        uses: actions/upload-artifact@v4
        with:
          name: outdated-dependencies
          path: |
            outdated-*.json
